export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const LOAN_APPROVAL_SUCCESS='LOAN_APPROVAL_SUCCESS';
export const LOAN_APPROVAL_FAILURE='LOAN_APPROVAL_FAILURE';